User interfaces
Nta1e/Fast-food-fast pull request #8
Opened 2018-09-11 18:01 UTC by NtaleShadik

This delivers user interfaces for the Fast-food-fast app

2018-09-11 21:02 UTC, sekayasin commented
hello bravo on the hardwork bro,..  About the admin link on the home page, i think yo exposing the admin url == attracting hackers!.. i think admins must have a special url known to them only to login and manage stuff..

2018-09-12 03:20 UTC, Nta1e commented
Yeah..was just improvising but the admin will be given different login credentials later on if you know what i mean

2018-09-12 06:11 UTC, okellogabrielinnocent approved these changes

2018-09-12 06:13 UTC, okellogabrielinnocent reviewed
Can the make order form be put to its own page such that after making an order it should return to orders made

2018-09-12 06:31 UTC, NtaleShadik commented
I can do that but then a popup can do the same thing..If the user wants to make an order, the model pops up and then after making the order he's returned to the orders  page

2018-09-12 06:39 UTC, okellogabrielinnocent approved these changes

2018-09-12 10:09 UTC, Kasulejoseph commented
hey shadik, your work is pretty awesome.. i like the java script implemented and the way you simplified your work and remains excellent is quit amazing. however, your are still missing some functions to the app like admin--delete,edit,and add. u only have for users adding orders..  if u want to retain the ones you designed for users then u should make a copy to the admin side also.

2018-09-12 10:29 UTC, NtaleShadik commented
Oooh Joseph..thanks for the reminder, I hadn't noticed that
working on it now

2018-09-12 19:36 UTC, Nta1e commented
Done...you can check it out now 😉

2018-09-12 21:24 UTC, Ivankivu requested changes

2018-09-12 21:24 UTC, Ivankivu commented on UI/admin_edit.html
> +<a href="""><button class=" btn-6" onclick="Deleted()">Delete</button></a>
(") please take care of this small extra tag as it can cause problems. so far it is good progress

2018-09-12 21:24 UTC, Ivankivu commented on UI/admin_edit.html
> +<a href="""><button class=" btn-6" onclick="Deleted()">Delete</button></a>
(") as u can see it is recurring here

2018-09-13 07:13 UTC, Phionamary reviewed
The code looks good to me, except for the extra tags that Ivan mentioned. They seem to be recurring in a lot of the forms, and this begs the question, "Have you tried to run your codes in the browser to see if they work?". Please work on these, and if you have then go ahead and merge

2018-09-13 10:18 UTC, Nta1e commented on UI/admin_edit.html
> +<a href="""><button class=" btn-6" onclick="Deleted()">Delete</button></a>
oooh..problem came when copying table rows..will fix that soon, currently my pc isn't booting

2018-09-18 11:51 UTC, merged